### ISSUE TITLE
About Page Casey Edits

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#117]
**Our Story Section**
- [x] text left aligned
- [x] switch background to pink instead of light pink
- [x] white box around the content
- [x] fix bug with object-fit on the left.
- [x] switch image for .mp4 of her eating donut slowly

**Other Stuff**
- [x] footer: Poke Around and Touch Us are misaligned. 
- [x] nav bar: the profile/login icon is non-visible. 
- [x] innuendo section: left align text
- [x] about page has stray section
- [x] The gift card image on the home page is like... 10px shorter than the other ones for some reason

**Comment by ckettler11** [comment]
@jordanlambrecht I toggled off 3 sections that seemed "stray" on page.about.liquid. If those have content on the live site be sure to uncomment them.
