### ISSUE TITLE
footer text should have a scroll for visibility or different color

### ISSUE THREAD

**Issue by mirandaarden** [pixelbakery/hollyshealthyholes#20]
light pink on yellow is v hard to read

**Comment by jordanlambrecht** [comment]
See what you think now. It's yellow on light pink.

**Comment by mirandaarden** [comment]
Am I high or is it light pink on dark pink? I think if it was yellow on dark pink that would be good, I'm specifically talking about the HHH logo in the bottom right if that wasn't clear
