### ISSUE TITLE
MOBILE: Header breaks as you scroll downwards

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#26]

**Comment by ckettler11** [comment]
@jordanlambrecht clarification: should the mobile header be "sticky" in the same manner as the desktop one?

**Comment by jordanlambrecht** [comment]
@ckettler11 I have it set to not be sticky currently just because the logo takes up so much room. Maybe we have the hamburger menu sticky but allow the logo to scroll off page?
