### ISSUE TITLE
Update Product Pricing

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#41]
Stuff your box - 
doz - $36 NO MATTER WHAT
half - $20

Originals - 
doz - $28
half - $16.50

Specialties -
doz - $34
half - $19.50

Need to confirm price of vegan donuts. I'm assuming they follow the same structure as specialty.

**Comment by mirandaarden** [comment]
[Pixel Bakery Design Studio Mail - Fwd_ pricing variables.pdf](https://github.com/pixelbakery/hollyshealthyholes/files/5284771/Pixel.Bakery.Design.Studio.Mail.-.Fwd_.pricing.variables.pdf)

**Comment by mirandaarden** [comment]
[Pixel Bakery Design Studio Mail - Fwd_ FW_ Holly's Healthy Holes.pdf](https://github.com/pixelbakery/hollyshealthyholes/files/5284797/Pixel.Bakery.Design.Studio.Mail.-.Fwd_.FW_.Holly.s.Healthy.Holes.pdf)

**Comment by jordanlambrecht** [comment]
Need to track down cost of CBD donuts
