### ISSUE TITLE
COPY: Homepage - yellow section

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#48]
- "DONUTS MADE WITH STUFF YOU ACTUALLY RECOGNIZE"
- paragraph text
- button text

**Comment by mchristensen11** [comment]
**Donuts Made with Stuff you Actually Recognize**

You could say our little company is a lot like a donut: we’ve got a transparent center. We make donuts with ingredients like coconut oil, egg whites, pumpkin, unsweetened applesauce, honey, apple cider vinegar—all the good stuff you can pronounce, all gluten free. 

**_Peep the full ingredients list_**
