### ISSUE TITLE
COPY: Homepage - Pink Section

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#50]
- header: #CheatEveryDay
- Check body copy

**Comment by mchristensen11** [comment]
What you eat matters. How good it makes you feel matters. And the really good stuff should be in your life as much as possible. We believe using food as medicine, and as a form of love and respect to your own self is important, no matter if you’re a health nut, a passionate vegan, or eating gluten-free.
