### ISSUE TITLE
COPY: Gift Card

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#53]
url: https://hollys-healthy-holes.myshopify.com/products/gift-card-1

-Need product description

**Comment by jordanlambrecht** [comment]
All product page copy has to be done in Shopventory, otherwise it'll be overwritten

**Comment by mchristensen11** [comment]
**GIFT CARD**

Gifting some Healthy Holes? Omg, you’re too sweet. 

Gift cards are delivered by email and contain instructions to redeem them at checkout.
Our gift cards have no additional processing fees.
