### ISSUE TITLE
COPY: Ingredients Page

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#58]
url: https://hollys-healthy-holes.myshopify.com/pages/ingredients

This page will have three different sections, one for each donut category. The ingredients of each donut will be listed out in those sections as well as the individual product pages. 

- blurb for each section
- an ingredient list for each donut that I can copy/paste when I make my way to that page

**Comment by mchristensen11** [comment]
****As far as I know, we only have info for ingredients that make up the dough, not anything for toppings.** 

**WHAT'S IN A BASIC GF* DONUT:**

*basic, gluten-free..NOT a basic girlfriend

100% pure whey protein isolate, Bob’s Red Mill gluten-free 1-1 baking flour (Sweet White Rice Flour, Whole Grain Brown Rice Flour, Potato Starch, Whole Grain Sorghum Flour, Tapioca Flour, Xanthan Gum), coconut oil, eggs, egg whites, pumpkin, chia seeds, unsweetened applesauce, honey, pure stevia extract, erythritol, apple cider vinegar, baking powder, baking soda, pure vanilla extract, Himalayan pink salt, cinnamon. 

**WHAT'S IN A MAGICAL VEGAN DONUT:**

Vegan protein blend (pea protein, brown rice protein),  Bob’s Red Mill gluten-free 1-1 baking flour (Sweet White Rice Flour, Whole Grain Brown Rice Flour, Potato Starch, Whole Grain Sorghum Flour, Tapioca Flour, Xanthan Gum), coconut oil, Enjoy Life vegan chocolate chips (cane sugar, unsweetened chocolate), ground flax seed, pumpkin puree, unsweetened applesauce, monkfruit extract, pure stevia extract, erythritol, apple cider vinegar, baking powder, baking soda, pure vanilla extract, Himalayan pink salt, cinnamon. 

**Depending on flavor, ingredients may include cocoa powder, natural ground peanut butter, additional spices and natural extracts. 

**Does not include glaze/toppings.

**Comment by mchristensen11** [comment]
As far as I know, we only have info for ingredients that make up the dough, not anything for toppings.
