### ISSUE TITLE
COPY: About Page - Hero Section

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#61]
url: https://hollys-healthy-holes.myshopify.com/pages/about
section: DONUTS MADE WITH STUFF YOU ACTUALLY RECOGNIZE

- Clean up / decide on section header title
- add more copy to blurb

**Comment by mchristensen11** [comment]
Do we need this? Not sure if you need a big hero after the "About" Header. If could go right into Holly's bio
