### ISSUE TITLE
COPY: About Page - Find Our Donuts

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#63]
- header title 
- blurb
- check all links to make sure they go to the right place
- check all addresses
- This section is going to get cleaned up. the cards will be horizontal instead

**Comment by mchristensen11** [comment]
**FIND OUR HOLES**

Good news: There are a ton of sweet locations around Nebraska where you can snag our protein donuts! Find your fave below, and put the pedal to the metal.

**Comment by mchristensen11** [comment]
Is that title too aggressive? Ha
