### ISSUE TITLE
COPY: About Page - IT'S DONUT TIME

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#64]
url: https://hollys-healthy-holes.myshopify.com/pages/about

- Do we like the section title?
- blurb of copy under title
- remove CBD-infused donuts
- Need to select photos for the BG images

**Comment by mchristensen11** [comment]
**IT’S DONUT TIME**

Gluten free. Natural, whole food sources. Crafted with love. 

You really can’t go wrong—what strikes your fancy?
