### ISSUE TITLE
COPY: Wholesale Page

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#65]
url: https://hollys-healthy-holes.myshopify.com/pages/wholesale

This page will have order requirements for wholesale/catering requests along with a contact form. Need to figure out what Holly wants for those rules and see if there's an app to potentially handle all that. For now, a contact form and some copy will suffice.

**Comment by mchristensen11** [comment]
Missing a big opportunity for HOLE-SALE ORDERS

**Comment by mchristensen11** [comment]
**HOLE-SALE ORDERS**

Your shop probably needs our donuts in its life. Shoot us a message, and we’ll talk wholesale. Can’t wait!
