### ISSUE TITLE
DESIGN & COPY: Decide where to put contact form

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#67]
Do we want the contact form on the about page with in-page links or it's own separate page? Thoughts? We'll need copy either way.

**Comment by mchristensen11** [comment]
**CONTACT US**

Questions? Concerns? Dream flavor suggestions? Hit us up.

**Comment by mchristensen11** [comment]
Could work either way. If we need to cut down number of pages, I'd put in on the About.
