### ISSUE TITLE
COPY: About Page - Innuendo

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/hollyshealthyholes#68]
Need a section on the about page that explains the significance behind the name and why it's an intentional innuendo. Could reference her brand exploration survey for this. Jordan: update link on home page to direct to this

**Comment by mchristensen11** [comment]
**YES, WE KNOW OUR NAME IS AN INNUENDO**

Love it or leave it, we like it that way.

I mean, c’mon, men do it all the time. Hooters? Just Good Meats? KUM & GO? 

If they can do it, why can’t we? Let’s talk about normalizing women’s sexuality!
